from django.urls import path
from . import views
from .views import autocomplete
from django.conf.urls.static import static
from django.conf import settings
#from django.contrib.sitemaps.views import sitemap
#from .sitemaps import PostSitemap



urlpatterns = [
    path('', views.index, name = 'index'),
    path('article/<str:slug>' , views.detail, name ='detail'),
    path('contact/', views.contact, name='contact'), 
    path('doctors/', views.doctors, name='doctors'),
    path('doctors/<uuid:doctor_id>/', views.doctor_detail, name='doctor_detail'),
    path('job_detail/<uuid:career_id>/',views.job_detail, name='job_detail'),
    path('caritas-cancer-institute',views.caritas_cancer_institute, name='caritas_cancer_institute'),
    path('caritas-heart-institute',views.caritas_heart_institute, name='caritas_heart_institute'),
    path('caritas-neuro',views.caritas_neuro, name='caritas_neuro'),
    path('caritas-gastro',views.caritas_gastro, name='caritas_gastro'),
    path('caritas-orthopaedics',views.caritas_orthopaedics, name='caritas_orthopaedics'),
    path('caritas-nephrology',views.caritas_nephrology, name='caritas_nephrology'),
    path('caritas-urology',views.caritas_urology, name='caritas_urology'),
    path('caritas-rheumatology',views.caritas_rheumatology, name='caritas_rheumatology'),
    path('caritas-paediatrics',views.caritas_paediatrics, name='caritas_paediatrics'),
    path('caritas-general-medicine',views.caritas_generalmedicine, name='caritas_generalmedicine'),
    path('caritas-ent-audiology',views.caritas_ENT, name='caritas_ENT'),
    path('endocrinology',views.endocrinology, name='endocrinology'),
    path('neonatology',views.neonatology, name='neonatology'),
    path('ophthalmology',views.ophthalmology, name='ophthalmology'),
    
    path('emergency-medicine',views.emergency_medicine, name='emergency_medicine'),
    path('dental',views.dental, name='dental'),
    path('pathology',views.pathology, name='pathology'),
    path('psychiatry', views.psychiatry, name='psychiatry'),
    path('plastic-microvascular',views.plastic_microvascular, name='plastic_microvascular'),
    path('pulmonology', views.pulmonology, name='pulmonology'),
    
    path('about-caritas', views.about_caritas, name='about_caritas'),
    path('gynaecology', views.gynaecology, name='gynaecology'),
    path('dermatology', views.dermatology, name='dermatology'),
    path('anaesthesiology', views.anaesthesiology, name='anaesthesiology'),
    path('physicalmedicine', views.physicalmedicine, name='physicalmedicine'),
    path('criticalcare', views.criticalcare, name='criticalcare'),
    path('generalsurgery', views.generalsurgery, name='generalsurgery'),
    
    path('radiology', views.radiology, name='radiology'),
    path('blood-bank', views.blood, name='blood'),
    path('clinical-nutrition', views.clinical, name='clinical'),
    path('physiotherapy', views.physiotherapy, name='physiotherapy'),
    path('organ', views.organ, name='organ'),
    path('insurance', views.insurance, name='insurance'),
    path('secondopinion', views.secondopinion, name='secondopinion'),
    path('pastoralcare', views.pastoralcare, name='pastoralcare'),
    path('stroke-help-line-in-kottayam', views.stroke, name='stroke'),
    path('director-message', views.director_message, name='director_message'),
    path('governing-body', views.governing_body, name='governing_body'),
    path('quality-control', views.quality_control, name='quality_control'),
    
    path('articles/', views.articles, name='articles'),
    path('dnb/', views.dnb, name='dnb'),
    path('college-of-nursing/', views.caritasnursing, name='caritasnursing'),
    path('health-checkup-packages', views.health_package, name='health_package'),
    path('college-of-pharmacy', views.pharmacy, name='pharmacy'),
    path('international_patients', views.international_patients, name='international_patients'),
    path('international_patients_arabic', views.international_patients_arabic, name='international_patients_arabic'),
    path('search_doctors/', views.search_doctors, name='search_doctors'),
    path('enquire_form/', views.enquire_form, name='enquire_form'),
    path('directions/', views.directions, name='directions'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('caritas-social-responsibility/', views.charity, name='charity'),
    path('career/', views.career, name='career'),
    path('biomedical/', views.biomedical, name='biomedical'),
    path('caritas-support-team/', views.support, name='support'),
    path('complaints/', views.complaints, name='complaints'),
    path('ethics-committee/', views.ethics, name='ethics'),
    path('caritas-family-hospital/', views.family, name='family'),
    path('caritas-hdp-hospital/', views.caritashdp, name='caritashdp'),
    path('caritaskkm/', views.caritaskkm, name='caritaskkm'),
    path('open-positions/', views.open_positions, name='open_positions'),
    path('senior-executive/', views.senior_executive, name='senior_executive'),
    path('caritas-allied-health-science/', views.paramedical, name='paramedical'),
    path('caritas-home-care/', views.homecare, name='homecare'),
    path('video-consultation/', views.video_consultation, name='video_consultation'),
    path('visitors-guide/', views.visitors_guide, name='visitors_guide'),
    path('milestones/', views.milestones, name='milestones'),
    path('caritas-mortuary-services/', views.mortuary_services, name='mortuary_services'),
    path('privacy-policy/', views.privacy, name='privacy'),
    path('terms & conditions/', views.terms_conditions, name='terms_conditions'),
    path('news & events/', views.news_events, name='news_events'),
    path('faq/', views.faq, name='faq'),
    path('patients-testimonials/', views.patients_testimonials, name='patients_testimonials'),
    path('achievements/', views.achievements, name='achievements'),
    path('search_results', views.search_results, name='search_results'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('search_jobs/', views.search_jobs, name='search_jobs'),
    #path('submit_application/', views.submit_application, name='submit_application'),
    path('community-medicine',views.community_medicine, name='community_medicine'),
    path('testimonials/', views.testimonials, name='testimonials'),
    path('gallery/', views.gallery, name='gallery'),
    path('album/<int:album_id>/', views.album_detail, name='album_detail'),
    path('filter-doctors/', views.filter_doctors, name='filter_doctors'),
    path('research-development/', views.research_development, name='research_development'),
    path('interventional-radiology/', views.interventional, name='interventional'),
   
    path('geriatric-medicine/', views.geriatric_medicine, name='geriatric_medicine'),
    path('caritashospitaldoctors/<uuid:doctor_id>/', views.caritashospitaldoctor_detail, name='caritashospitaldoctor_detail'),
    path('success/', views.success, name='success'),
   # path('sitemap.xml', sitemap, {'sitemaps': {'post': PostSitemap}}, name='django.contrib.sitemaps.views.sitemap'),
   
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

