# Generated by Django 3.2.22 on 2023-10-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_title',
            new_name='title',
        ),
    ]
