# Generated by Django 3.2.22 on 2023-10-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0002_rename_cat_title_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='caritasapp.category'),
            preserve_default=False,
        ),
    ]
