# Generated by Django 3.2.22 on 2023-10-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0003_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
    ]
