# Generated by Django 3.2.22 on 2023-10-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0006_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='doctor',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
