# Generated by Django 3.2.22 on 2023-10-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0008_contact_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritasapp.department'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritasapp.doctor'),
        ),
    ]
