# Generated by Django 3.2.22 on 2023-10-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0009_auto_20231027_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='doctor',
        ),
    ]
