# Generated by Django 3.2.22 on 2023-10-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0014_auto_20231027_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
    ]
