# Generated by Django 3.2.22 on 2023-10-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0016_auto_20231027_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
