# Generated by Django 3.2.22 on 2023-10-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0018_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='enquire',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
