# Generated by Django 3.2.22 on 2023-10-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0019_auto_20231028_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caritasapp.department'),
        ),
    ]
