# Generated by Django 3.2.22 on 2023-10-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0021_alter_contact_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritasapp.department', null=True),
        ),
    ]
