# Generated by Django 3.2.22 on 2023-10-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0023_alter_contact_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='img/Default.png', null=True, upload_to='doctors/'),
        ),
    ]
