# Generated by Django 3.2.22 on 2023-11-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0028_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caritasapp.department'),
        ),
    ]
