# Generated by Django 3.2.22 on 2023-11-10 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0030_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('job_type', models.CharField(max_length=100)),
                ('job_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caritasapp.jobtype'),
        ),
    ]
