# Generated by Django 3.2.22 on 2023-11-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0031_auto_20231110_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='key_responsibilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='preferred_skills',
            field=models.TextField(),
        ),
    ]
