# Generated by Django 3.2.22 on 2023-11-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0032_auto_20231110_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
