# Generated by Django 3.2.22 on 2023-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0033_doctor_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('agree_terms', models.BooleanField()),
                ('page_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='job_discription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='key_responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='preferred_skills',
            field=models.TextField(blank=True),
        ),
    ]
