# Generated by Django 3.2.22 on 2023-11-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0039_alter_sliderimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(blank=True, max_length=620),
        ),
    ]
