# Generated by Django 3.2.22 on 2023-11-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0040_auto_20231125_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('caption', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=620)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
