# Generated by Django 3.2.23 on 2023-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0042_alter_mobilesliderimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bags', models.CharField(max_length=100)),
                ('yellow_bags', models.CharField(max_length=100)),
                ('red_bags', models.CharField(max_length=100)),
                ('white_bags', models.CharField(max_length=100)),
                ('brownish_yellow_bags', models.CharField(max_length=100)),
                ('blue_bags', models.CharField(max_length=100)),
                ('month_year', models.DateField(blank=True, null=True, verbose_name='Month and Year')),
            ],
        ),
        migrations.CreateModel(
            name='HomeCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_length', models.CharField(max_length=100)),
                ('patient_satisfaction', models.CharField(max_length=100)),
                ('cauti', models.CharField(max_length=100)),
                ('vap', models.CharField(max_length=100)),
                ('clabsi', models.CharField(max_length=100)),
                ('ssi', models.CharField(max_length=100)),
                ('pressure_ulcers_afteradmission', models.CharField(max_length=100)),
                ('compliance_hand_hygiene', models.CharField(max_length=100)),
                ('month_year', models.DateField(blank=True, null=True, verbose_name='Month and Year')),
            ],
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.TextField(blank=True)),
                ('investigators', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='order',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(blank=True, to='caritasapp.Hospital'),
        ),
    ]
