# Generated by Django 3.2.23 on 2023-12-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0043_auto_20231227_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
