# Generated by Django 3.2.23 on 2024-01-31 10:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('caritasapp', '0045_internationalform'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='doctors_images/')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='Department_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internationalform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='achievements_and_expertise',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='awards_and_recognitions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CaritasHospitalDoctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('professional_qualifications', models.CharField(blank=True, max_length=1000)),
                ('achievements_and_expertise', models.CharField(blank=True, max_length=1000)),
                ('awards_and_recognitions', models.CharField(blank=True, max_length=1000)),
                ('language', models.CharField(blank=True, max_length=255)),
                ('order', models.CharField(blank=True, max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('available_timings', models.TextField(blank=True)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='caritasapp.department')),
                ('hospitals', models.ManyToManyField(blank=True, to='caritasapp.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='BookConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('dob', models.DateField(blank=True, null=True)),
                ('op_number', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True)),
                ('agree_terms', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caritasapp.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caritasapp.doctor')),
            ],
        ),
    ]
